routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HorarioController;
use App\Http\Controllers\PacienteController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('horarios', HorarioController::class);

Route::resource('pacientes', PacienteController::class);

app/Http/Controllers/HorarioController.php
<?php

namespace App\Http\Controllers;

use App\Models\Horario_Atencion;
use Illuminate\Support\Facades\Validator;
use Illuminate\Http\Request;

class HorarioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $horarios = Horario_Atencion::all();
        return view('horarios.index', compact('horarios'));
        //return $horarios;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('horarios.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $v = Validator::make($request->all(), [
            'dia_horario_atencion' => 'date',
            'inicio_horario_atencion' => 'required',
            'fin_horario_atencion' => 'required',
        ]);

        if ($v->fails()) {
            return redirect()->back()->withErrors($v->errors())->withInput();
        } else {
            Horario_Atencion::create($request->all());
            return redirect()->route('horarios.index')->with('success', 'Horario creado exitosamente!!');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Horario_Atencion $horario)
    {
        return view('horarios.edit', compact('horario'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $horario = Horario_Atencion::find($id);
        $horario->update($request->all());

        return redirect()->route('horarios.index')->with('success', 'Horario actualizado exitosamente!!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $horario = Horario_Atencion::find($id);
        $horario->delete();

        return redirect()->route('horarios.index')->with('success', 'Horario eliminado exitosamente!!');
    }
}

resources/views/horarios/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div align="center">
            <h2>Agregar Nuevo Horario_11</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('horarios.index') }}"> Regresar</a>
        </div>
    </br>
        

        <form action="{{ route('horarios.store') }}" method="POST">
            @csrf


            <!-- **************************** inicio VALIDACIONES 1_ required-->
            <!-- 

            <div class="row">
                <div>
                    <div class="form-group">
                        <strong>Día Atención:</strong>
                        <input type="date" name="dia_horario_atencion" class="form-control"
                            placeholder="Ingrese el día de atención" 
                            value="{{ old('dia_horario_atencion') }}" required>  
                        @error('dia_horario_atencion')
                            <p class="error-message">{{ $message }}</p>
                        @enderror
                    </div>
                </div>

                <div>
                    <div class="form-group">
                        <strong>Hora Inicio de Atención:</strong>
                        <input type="time" name="inicio_horario_atencion" class="form-control"
                            value="{{ old('inicio_horario_atencion') }}" required>
                        @error('inicio_horario_atencion')
                            <p class="error-message">{{ $message }}</p>
                        @enderror
                    </div>
                </div>
       
                <div>
                    <div class="form-group">
                        <strong>Hora Fin de Atención:</strong>
                        <input type="time" name="fin_horario_atencion" class="form-control"
                        value="{{ old('fin_horario_atencion') }}" required>
                        @error('fin_horario_atencion')
                        <p class="error-message">{{ $message }}</p>
                        @enderror
                    </div>
                </div>
                
                 -->
            <!-- ********************************  FIN_VALIDACIONES_1 required  -->


            <!-- ******************************** INICIO_VALIDACIONES_2-->
            
            <div class="row">
                <div>
                    <div class="form-group">
                        <strong>Día Atención:</strong>
                        <input type="date" name="dia_horario_atencion" class="form-control"
                            placeholder="Ingrese el día horario de atención" 
                           
                        @error('dia_horario_atencion')
                        <p>{{ $message }}</p>
                        @enderror
                    </div>
                </div>

                <div>
                    <div class="form-group">
                        <strong>Hora Inicio de Atención:</strong>
                        <input type="time" name="inicio_horario_atencion" class="form-control"
                        placeholder="Ingrese hora inicio día de atención" 

                        @error('inicio_horario_atencion')
                        <p>{{ $message }}</p>
                        @enderror
                    </div>
                </div>
       
                 <div>
                    <div class="form-group">
                        <strong>Hora Fin de Atención:</strong>
                        <input type="time" name="fin_horario_atencion" class="form-control"
                        placeholder="Ingrese hora fin de atención" 
        
                        @error('fin_horario_atencion')
                            <p>{{ $message }}</p>
                        @enderror
                    </div>
                </div>
            
            
               <!-- ******************************** FIN_VALIDACIONES_2-->

           

             
             <!-- ******************************** inicio milenght
            ingrese minimo dos caracteres- -->

                
                <div>
                </br> </br>
                    <div class="form-group">
                        <strong>Validación 1: "minlegth"  </strong>
                        <input type="text" name="fin_horario_atencion" class="form-control"
                        placeholder="Ingrese hora fin de atención" minlength="2">
                
                        @error('fin_horario_atencion') 
                            <p> {{ $message }}</p>
                        @enderror
                    </div>
                </div>
            
    <!-- ******************************** fin minlenght-->

 <!-- ******************************** inicio maxlenght
        Ingrese mMAXIMO 5 caracteres -->

                
            <div>
            </br> </br>
                <div class="form-group">
                    <strong>Validación 2: "maxlegth" > máximo 5 caracteres</strong>
                    <input type="text" name="fin_horario_atencion" class="form-control"
                    placeholder="Ingrese hora fin de atención" maxlength="5">
            
                    @error('fin_horario_atencion') 
                        <p> {{ $message }}</p>
                    @enderror
                </div>
            </div>
        
<!-- ******************************** fin minlenght-->

 <!-- ******************************** inicio maxlenght
        Ingrese solamente números- -->

                
        <div>
        </br> </br>
            <div class="form-group">
                <strong>Validación 3: "max" > ingrese máximo 5 caracteres "Solo numeros"</strong>
                <input type="number" name="fin_horario_atencion" class="form-control"
                placeholder="Ingrese hora fin de atención" max="5">
        
                @error('fin_horario_atencion') 
                    <p> {{ $message }}</p>
                @enderror
            </div>
        </div>
    
<!-- ******************************** fin maxlenght-->

 <!-- ******************************** inicio minlenght
        Ingrese solamente números- -->

                
        <div>
        </br> </br>
            <div class="form-group">
                <strong>Validación 4: "min" > ingrese mínimo 4 caracteres "Solo numeros"</strong>
                <input type="text" name="fin_horario_atencion" class="form-control"
                placeholder="Ingrese hora fin de atención" min="4">
        
                @error('fin_horario_atencion') 
                    <p> {{ $message }}</p>
                @enderror
            </div>
        </div>
    
<!-- ******************************** fin minlenght-->

 <!-- ******************************** inicio minlenght
        Validaciones con esilos-->

                
        <div>
        </br> </br>
            <div class="form-group">
                <strong>Validación 5: OBSERVACIONES:  Validaciones con estilos </strong>
                <input type="text" name="fin_horario_atencion" class="form-control"
                placeholder="Ingrese las observaciones" required>
        
                @error('fin_horario_atencion') 
                    <p> {{ $message }}</p>
                @enderror
            </div>
        </div>
    
<!-- ******************************** fin minlenght-->


 <!-- ******************************** inicio minlenght
        Validaciones con esilos-->

                
        <div>
        </br> </br>
            <div class="form-group">
                <strong>Validación 6: "pattern"  Tiene Discapacidad, escriba si o no </strong>
                <input type="text" name="fin_horario_atencion" class="form-control"
                placeholder="Ingrese las observaciones" pattern="si">
        
                @error('fin_horario_atencion') 
                    <p> {{ $message }}</p>
                @enderror
            </div>
        </div>
    
<!-- ******************************** fin minlenght-->

 <!-- ******************************** inicio minlenght
        Validaciones con esilos-->

                
        <div>
        </br> </br>
            <div class="form-group">
                <strong>Validación 7: "pattern" Ingrese el numero de telefono +123 123456789</strong>
                <input type="text" name="fin_horario_atencion" class="form-control"
                placeholder="Ingrese las observaciones" pattern="[+][0-5]{3}[][+][0-5]{3}+">
        
                @error('fin_horario_atencion') 
                    <p> {{ $message }}</p>
                @enderror
            </div>
        </div>
    
<!-- ******************************** fin minlenght-->

<!-- ******************************** inicio minlenght
        Validaciones con esilos-->

                
        <div>
        </br> </br>
            <div class="form-group">
                <strong>Validación cedula:  060427904-2</strong>
                <input type="text" name="fin_horario_atencion" class="form-control"
                placeholder="Ingrese las observaciones" pattern="[0-9]{9}">
        
                @error('fin_horario_atencion') 
                    <p> {{ $message }}</p>
                @enderror
            </div>
        </div>
    
<!-- ******************************** fin minlenght-->







                




                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                </br>  </br>
                    <button type="submit" class="btn btn-primary">Guardar</button>
                </div>
            </div>








        </form>
    </div>
@endsection

resources/views/horarios/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Editar Horario de Atención</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('horarios.index') }}"> Regresar</a>
            </div>
        </div>
    </div>
    <form action="{{ route('horarios.update',$horario->id) }}" method="POST">
        @csrf
        @method('PUT')
         <div class="row">
            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Día Atención:</strong>
                    <input type="date" name="dia_horario_atencion" class="form-control" value="{{ $horario->dia_horario_atencion }}">
                </div>
            </div>
            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Hora Inicio Atención:</strong>
                    <input type="time" name="inicio_horario_atencion" class="form-control" value="{{ $horario->inicio_horario_atencion }}">
                </div>
            </div>
            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Hora Fin Atención:</strong>
                    <input type="time" name="fin_horario_atencion" class="form-control" value="{{ $horario->fin_horario_atencion }}">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
        </div>
    </form>
@endsection

resources/views/horarios/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <br />
        <h1 align="center">REPORTE DE HORARIOS DE ATENCIÓN _ h1</h1>
        <div>
            <a class="btn btn-success" href="{{ route('horarios.create') }}">Crear</a>
        </div>
        <br />
        @if (Session::get('success'))
            <div class="alert alert-success">
                <p>{{ Session::get('success') }}</p>
            </div>
        @endif
        <table class="table">
            <tr>
                <th>Id</th>
                <th>Dia Atención</th>
                <th>Hora Inicio Atención</th>
                <th>Hora Fin Atención</th>
                <th>Acciones</th>
            </tr>
            @foreach ($horarios as $horario)
                <tr>
                    <td>{{ $horario->id }}</td>
                    <td>{{ $horario->dia_horario_atencion }}</td>
                    <td>{{ $horario->inicio_horario_atencion }}</td>
                    <td>{{ $horario->fin_horario_atencion }}</td>
                    <td><a class="btn btn-primary" href="{{ route('horarios.edit',$horario) }}">
                            <i class="fa-solid fa-pen-to-square"></i>
                        </a>
                        <form action="{{ route('horarios.destroy',$horario->id) }}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-primary"><i class="fas fa-trash-alt"></i></button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </table>
    </div>
@endsection