routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HorarioController;
use App\Http\Controllers\PacienteController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('horarios', HorarioController::class);

Route::resource('pacientes', PacienteController::class);

app/Models/Paciente.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Paciente extends Model
{
    use HasFactory;
    protected $table = 'pacientes';
    protected $primaryKey = 'id';
    public $timestamps = false;
    protected $fillable = [
        'id',
        'nombres_paciente',
        'email_paciente',
        'ciudad_paciente',
        'telefono_id ',
    ];

    public function telefono(){
        return $this->belongsTo(Telefono::class);
    }

}

app/Http/Controllers/PacienteController.php
<?php

namespace App\Http\Controllers;

use App\Models\Paciente;
use Illuminate\Support\Facades\Validator;
use Illuminate\Http\Request;

class PacienteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pacientes = Paciente::all();
     /*   $pacientes = Paciente::select('*')
                    ->with('telefono')
                    ->get()
        return $pacientes;
        */


        return view('pacientes.index', compact('pacientes'));
        //return $horarios;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pacientes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     
     *******************************************************************************************    */



    public function store(Request $request)
    {
        $v = Validator::make($request->all(), [
            'nombres_paciente' => 'required',
            'email_paciente' => 'required',
            'ciudad_paciente' => 'required',
            'telefono_id' => 'required',

        ]);

        if ($v->fails()) {
            return redirect()->back()->withErrors($v->errors())->withInput();
        } else {
            Paciente::create($request->all());
            return redirect()->route('pacientes.index')->with('success', 'Horario Paciente creado exitosamente!!');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Paciente $paciente)
    {
        return view('pacientes.edit', compact('paciente'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $paciente = Paciente ::find($id);
        $paciente->update($request->all());

        return redirect()->route('pacientes.index')->with('success', 'Horario pacientes actualizado exitosamente!!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $paciente = Paciente::find($id);
        $paciente->delete();

        return redirect()->route('pacientes.index')->with('success', 'Horario pacientes eliminado exitosamente!!');
    }
}

resources/views/pacientes/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div align="center">
            <h2>Agregar Nuevo Paciente_ Crear </h2>
        </div>
        <div class="pull-right">
        </br>
            <a class="btn btn-primary" href="{{ route('pacientes.index') }}"> Regresar</a>
        
        </br> </br> 
        </div>

        <form action="{{ route('pacientes.store') }}" method="POST">
            @csrf

            <div class="row">
                <div>
                    <div class="form-group">
                        <strong>Nombre Paciente :</strong>
                        <input type="varchar" name="nombres_paciente" class="form-control"
                            placeholder="Diego Vizueta" value="{{ old('nombres_paciente') }}" required>
                        @error('nombres_paciente')
                            <p class="error-message">{{ $message }}</p>
                        @enderror
                    </div>
                </div>

                <div>
                    <div class="form-group">
                        <strong>Email Paciente:</strong>
                        <input type="varchar" name="email_paciente" class="form-control"
                        placeholder="diegovizueta@gmail.com"
                            value="{{ old('email_paciente') }}" required>
                        @error('email_paciente')
                            <p class="error-message">{{ $message }}</p>
                        @enderror
                    </div>
                </div>

                <div>
                    <div class="form-group">
                        <strong>Ciudad Paciente:</strong>
                        <input type="varchar" name="ciudad_paciente" class="form-control"
                        placeholder="Quito"
                            value="{{ old('ciudad_paciente') }}" required>
                        @error('ciudad_paciente')
                            <p class="error-message">{{ $message }}</p>
                        @enderror
                    </div>
                </div>

               
                <div>
                    <div class="form-group">
                        <strong>Telefono Paciente:</strong>
                        <input type="tel" name="telefono_id" class="form-control"
                        placeholder="0984649924"
                        value="{{ old('telefono_id ') }}" required>
                         <!--    value="{{ old('telefono_id ') }}" pattern="[+][0-5]{3}[0-9]{9}"> -->
                        @error('telefono_id ')
                            <p class="error-message">{{ $message }}</p>
                        @enderror
                    </div>
                </div> 
            
             <!--  -->
     
                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                </br>  </br>
                    <button type="submit" class="btn btn-primary">Guardar</button>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/pacientes/edit.blade.php
@extends('layouts.app')
@section('content')




  <div class="container">
        <div align="center">
            <h2> Editar Horario de Atención_ 1</h2>
        </div>
   
     
            <div class="pull-right">
            </br>
                <a class="btn btn-primary" href="{{ route('pacientes.index') }}"> Regresar</a>
            </div>
        </div>
    </div>
</div>


</div>
    <form action="{{ route('pacientes.update',$paciente->id) }}" method="POST">
        @csrf
        @method('PUT')
         <div class="row">
            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Nombre de paciente:</strong>
                    <input type="varchar" name="nombres_paciente" class="form-control" value="{{ $paciente->nombres_paciente }}">
                </div>
            </div>

            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Email de paciente:</strong>
                    <input type="varchar" name="email_paciente" class="form-control" value="{{ $paciente->email_paciente }}">
                </div>
            </div>

            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Ciudad Paciente:</strong>
                    <input type="varchar" name="ciudad_paciente" class="form-control" value="{{ $paciente->ciudad_paciente }}">
                </div>
            </div>

                <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                    <div class="form-group">
                        <strong>Telefono Paciente:</strong>
                        <input type="int" name="telefono_id" id="telefono_id" class="form-control" value="{{ $paciente->telefono_id }}">
                    </div>
                </div>


                
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            </br>   </br>
              <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
        </div>
    </form>
@endsection

resources/views/pacientes/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <br />
        <h1 align="center">REPORTE DE PACIENTES_ INDEX_1</h1>
        <div>
            <a class="btn btn-success" href="{{ route('pacientes.create') }}">Crear</a>
        </div>
        <br />
        @if (Session::get('success'))
            <div class="alert alert-success">
                <p>{{ Session::get('success') }}</p>
            </div>
        @endif
        <table class="table">
            <tr>
                <th>Id</th>
                <th>Nombres Paciente</th>
                <th>Email Paciente</th>
                <th>Ciudad Paciente</th>
                <th>Teléfono Paciente</th>
                <th>Acciones</th>
            </tr>
            @foreach ($pacientes as $paciente)
                <tr>
                    <td>{{ $paciente->id }}</td>
                    <td>{{ $paciente->nombres_paciente }}</td>
                    <td>{{ $paciente->email_paciente }}</td>
                    <td>{{ $paciente->ciudad_paciente }}</td>
                    <td>{{ $paciente->telefono_id }}</td>
                    <td> <a class="btn btn-primary" href="{{route('pacientes.edit',$paciente)}}" >
                        <i class="fa-solid fa-pen-to-square"> </i>
                        </a>
                        <form action="{{ route('pacientes.destroy',$paciente->id )}}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-primary"> <i class="fas fa-trash-alt">  </i> </button>
                        </form>
                    </td>
                </tr>
            
            @endforeach
        </table>
    </div>
@endsection